name: infoboard
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  http:
  intl:
  path_provider:
  shared_preferences:
  url_launcher:
  auto_size_text:
  transparent_image:
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/happyface.png
    - assets/edsby.png
    - assets/splash.png
    - assets/bus.png

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 400
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 600
